version: '3'
services:

  # frontend:
  #   build: ./client
  #   command: npm start
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    command: npm start
    ports:
      - "4000:3000"
  
  mongodb:
    image: mongo
    volumes:
      - hindustan_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zuvaLabs

volumes:
  hindustan_data: