version: '3'
services:

  # frontend:
  #   build: ./client
  #   command: npm start
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    command: npm start
    ports:
      - "4000:3000"
  
  mongodb:
    image: mongo
    volumes:
      - hindustan_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zuvaLabs

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672  # RabbitMQ default port
      - 15672:15672  # RabbitMQ management console port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data
    environment:
      - RABBITMQ_DEFAULT_USER=root  # Set the desired username
      - RABBITMQ_DEFAULT_PASS=zuvaLabs  # Set the desired password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management

volumes:
  hindustan_data:
  rabbitmq_data:
