version: '3'
services:

  # frontend:
  #   build: ./client
  #   command: npm start
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    command: npm start
    ports:
      - "3000:3000"
  
  mongodb:
    image: mongo
    volumes:
      - data:/data/db

volumes:
  data: